
#======================================#
#========== Project settings ==========#
#======================================#

# 产品或项目名称、软件开发公司名称
productName: 目标绩效管理系统
companyName: 3000Dan

# 产品版本、版权年份
productVersion: V0.1
copyrightYear: 2019

#是否演示模式
customer: 绵阳市公安局
serverDepartment: 市局指挥中心
serverPhone: 0816-2498031

#是否演示模式
demoMode: false
test: true

#======================================#
#========== Server settings ===========#
#======================================#

server:

  port: 8980
  servlet:
    context-path: /js
  tomcat:
    uri-encoding: UTF-8
    
#======================================#
#========== Database sttings ==========#
#======================================#

# 数据库连接
jdbc: 
  
  # Mysql 数据库配置
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://47.244.133.160:3306/jeesite?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: Root123@123
  testSql: SELECT 1


#======================================#
#========== Spring settings ===========#
#======================================#

spring:
  
  # 应用程序名称
  application:
    name: jeesite-web
    
  # 当前环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles:    
    active: test
    
  # 打印横幅
  main:
    bannerMode: "off"
    # springboot 2.0 以后自动集成quartz 简化配置
    #定时任务数据持久化
  quartz:
    org:
      quartz:
        scheduler:
          instanceName: clusteredScheduler
          instanceId: AUTO
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          tablePrefix: QRTZ_
          isClustered: true
          clusterCheckinInterval: 10000
          useProperties: false
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 10
          threadPriority: 5
          threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
    #初始化表结构
#    jdbc:
#      initialize-schema: never
#      schema: classpath:mysql/quartz_tables.sql



# 日志配置
logging:
  config: classpath:config/logback-spring.xml

